name: vpf
description: VCS package format utilities
version: 0.1.0
repository: https://git.the-omnia.ru/omnia/vcs

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
# dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
